# Generated by Django 3.0.4 on 2020-03-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminProf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adsTitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='adsTitle')),
                ('adsFlyer', models.ImageField(upload_to='ads', verbose_name='ads picture')),
                ('adsInfo', models.CharField(blank=True, max_length=200, null=True, verbose_name='ads info')),
            ],
        ),
        migrations.RemoveField(
            model_name='barber',
            name='adsImage',
        ),
        migrations.RemoveField(
            model_name='barber',
            name='barberRules',
        ),
        migrations.AddField(
            model_name='barber',
            name='barberName',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Barber Name'),
        ),
    ]
